### ISSUE TITLE
Ficheros Images y images

### ISSUE THREAD

**Issue by Gbrl413** [miguelgomez75/24-25-IdSw1-SDR#1]
Tenemos dos ficheros de imagenes. o hay que diferenciarlos apropiadamente segun su contenido, o hay que unirlos en uno mismo para evitar problemas y confusion visual.

**Comment by miguelgomez75** [comment]
sí, dejámelo a mi que los unifico ahora, es que ahora mismo en uno están los diseños de interfaces que serían para más adelante y en el otro es donde tenemos los diagramas del modelo de dominio
